#priority 1
#Author - DekuxDev
#ModPack - DinosaurGang
#Script - RemoveAndHide
import crafttweaker.item.IItemStack;
import crafttweaker.item.IIngredient;

import mods.jei.JEI;

static hiddenItems as IIngredient[] = [

	<pyrotech:tongs_flint>,
	<pyrotech:flint_shovel>,
	<pyrotech:flint_pickaxe>,
	<pyrotech:flint_hoe>,
	<pyrotech:flint_axe>,
	<pyrotech:flint_sword>,
	<minecraft:flint_and_steel>,
	<pyrotech:material:10>,
	<immersiveengineering:metal_device0:3>,
	<primal_tech:bone_knife>,
	<primal_tech:bone_sword>,
	<primal_tech:bone_shears>,
	<primal_tech:bone_shovel>,
	<pyrotech:flint_hammer>,
	<pyrotech:bone_hoe>,
	<pyrotech:bone_axe>,
	<embers:dawnstone_anvil>,
	<pyrotech:bone_pickaxe>,
	<pyrotech:bone_shovel>,
	<pyrotech:bone_sword>,
	<pyrotech:bone_shears>,
	<pyrotech:worktable>,
	<pyrotech:worktable_stone>,
	<pyrotech:anvil_iron_plated>,
	<pyrotech:generated_slag_aluminum>,
	<pyrotech:generated_pile_slag_aluminum>,
	<pyrotech:generated_slag_copper>,
	<pyrotech:generated_pile_slag_copper>,
	<pyrotech:generated_slag_gold>,
	<pyrotech:generated_pile_slag_gold>,
	<pyrotech:generated_slag_iron>,
	<pyrotech:generated_pile_slag_iron>,
	<pyrotech:generated_slag_lead>,
	<pyrotech:generated_pile_slag_lead>,
	<pyrotech:generated_slag_nickel>,
	<pyrotech:generated_pile_slag_nickel>,
	<pyrotech:generated_slag_silver>,
	<pyrotech:generated_pile_slag_silver>,
	<pyrotech:generated_slag_uranium>,
	<pyrotech:generated_pile_slag_uranium>,
	<primal_tech:bone_pickaxe>,
	<pyrotech:crude_axe>,
	<pyrotech:crude_hoe>,
	<pyrotech:crude_pickaxe>,
	<pyrotech:crude_shovel>,
	<pyrotech:obsidian_axe>,
	<pyrotech:obsidian_hoe>,
	<pyrotech:obsidian_pickaxe>,
	<pyrotech:obsidian_shovel>,
	<pyrotech:obsidian_sword>,
	<actuallyadditions:item_helm_obsidian>,
	<actuallyadditions:item_chest_obsidian>,
	<actuallyadditions:item_boots_obsidian>,
	<actuallyadditions:item_pickaxe_obsidian>,
	<actuallyadditions:item_sword_obsidian>,
	<pyrotech:material:33>,
	<primal:obsidian_pickaxe>,
	<primal:obsidian_shovel>,
	<primal:obsidian_hoe>,
	<primal:obsidian_hatchet>,
	<primal:obsidian_axe>,
	<primal:obsidian_workblade>,
	<primal_tech:bone_axe>,
	<pyrotech:rock>,
	<pyrotech:rock:1>,
	<pyrotech:rock:2>,
	<pyrotech:rock:3>,
	<pyrotech:rock:6>,
	<pyrotech:rock:8>,
	<grimpack:wooden_multi_tool>,
	<minecraft:wooden_sword>,
	<betterwithmods:creative_generator>,
	<primal_tech:wood_club>,
	<grimpack:wood_hammer>,
	<grimpack:machete_wood>,
	<storagedrawers:upgrade_creative>,
	<storagedrawers:upgrade_creative:1>,
	<refinedstorage:controller:1>,
	<refinedstorage:portable_grid:1>,
	<refinedstorage:storage:4>,
	<refinedstorage:fluid_storage:4>,
	<refinedstorage:storage_disk:4>,
	<refinedstorage:fluid_storage_disk:4>,
	<refinedstorage:wireless_grid:1>,
	<refinedstorage:wireless_fluid_grid:1>,
	<refinedstorage:wireless_crafting_monitor:1>,
	<calculator:creativepowercube>,
	<cyberware:creative_battery>,
	<drpmedieval:wooden_lock>,
	<drpmedieval:wooden_key>,
	<embers:creative_ember_source>,
	<iceandfire:creative_dragon_meal>,
	<mowziesmobs:earth_talisman>,
	<overloaded:creative_generator>,
	<progressiveautomation:creative_rf_engine>,
	<libvulpes:creativepowerbattery>,
	<embers:stamper>,
	<embers:stamper_base>,
	<betterwithmods:aesthetic:5>,
	<botania:manatablet>,
	<botania:pool:1>,
	<enderio:block_decoration2:4>,
	<enderio:block_buffer:3>,
	<enderio:block_creative_spawner>,
	<enderio:block_cap_bank>.withTag({"enderio:energy": 50000000}),
	<extrautils2:itemcreativedestructionwand>,
	<extrautils2:itemcreativebuilderswand>,
	<extrautils2:passivegenerator:6>,
	<extrautils2:drum:4>,
	<extrautils2:spike_creative>,
	<extrautils2:creativechest>,
	<extrautils2:creativeenergy>,
	<extrautils2:creativeharvest>,
	<bigreactors:turbinecreativesteamgenerator>,
	<bigreactors:reactorcreativecoolantport>,
	<mekanism:basicblock:6>.withTag({tier: 4}),
	<mekanism:machineblock2:11>.withTag({tier: 4}),
	<mekanism:energycube>.withTag({tier: 4}),
	<mekanism:energycube>.withTag({tier: 4, mekData: {energyStored: 1.7976931348623157E308}}),
	<mekanism:gastank>.withTag({tier: 4}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "hydrogen"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "oxygen"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "water"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "chlorine"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfurdioxide"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfurtrioxide"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sulfuricacid"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "hydrogenchloride"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "ethene"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "sodium"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "brine"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "deuterium"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "tritium"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "fusionfuel"}}}),
	<mekanism:gastank>.withTag({tier: 4, mekData: {stored: {amount: 2147483647, gasName: "lithium"}}}),
	<rftools:flight_module>,
	<rftools:creative_screen>,
	<rftools:powercell_creative>,
	<thermalexpansion:capacitor:32000>,
	<thermalexpansion:reservoir:32000>,
	<thermalexpansion:satchel:32000>,
	<thermalfoundation:upgrade:256>,
	<armorplus:chainmail_helmet>,
	<armorplus:chainmail_chestplate>,
	<armorplus:chainmail_leggings>,
	<armorplus:chainmail_boots>,
	<armorplus:iron_helmet>,
	<armorplus:iron_chestplate>,
	<armorplus:iron_leggings>,
	<armorplus:iron_boots>,
	<armorplus:gold_helmet>,
	<armorplus:gold_chestplate>,
	<armorplus:gold_leggings>,
	<armorplus:gold_boots>,
	<armorplus:diamond_helmet>,
	<armorplus:diamond_chestplate>,
	<armorplus:diamond_leggings>,
	<armorplus:diamond_boots>,
	<thaumcraft:creative_flux_sponge>

];

function init() {
	for ingredient in hiddenItems {
		mods.jei.JEI.removeAndHide(ingredient);
	}
}